# Generated by Django 5.0.6 on 2024-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
